### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by DanPatten** [socs-dev-env/DoSOCS#13]
Having this issue calling ./DoSPDX 

``` 
    File "./DoSPDX.py", line 26, in <module>
    import spdx
    File "/spdx.py", line 55
    packageDescription=None),
                            ^
SyntaxError: invalid syntax
```
Running python 2.7.6 on Ubuntu 14.04. I can fix the issue by removing the ) after     packageDescription=None. I seem to have several other various issues running doSOCs out of the box. Is it related to the OS or python version? Thanks

**Comment by zwmcfarland** [comment]
Thanks for reporting the issue. I am not sure how that got in there. Regarding the other issues, please let us know if you see any other issues and we will get them fixed as soon as possible.
