### ISSUE TITLE
Unable to scan file

### ISSUE THREAD

**Issue by DanPatten** [socs-dev-env/DoSOCS#14]
If I run the following command:
/DoSPDX.py -p busybox-1.23.1.tar.bz2 --scanOption fossology --scan

I get the following:
```
 File "DoSPDX.py", line 145, in <module>
    main(sys.argv[1:])
  File "DoSPDX.py", line 134, in main
    spdxDoc.generateSPDXDoc(scanOption)

spdxDoc.generateSPDXDoc(scanOption)
TypeError: generateSPDXDoc() takes exactly 1 argument (2 given)
```

**Comment by vpenmatsa** [comment]
Missing scanOption parameter in generateSPDXDoc function in spdx.py class

**Comment by zwmcfarland** [comment]
For reference, this was fixed with https://github.com/socs-dev-env/DoSOCS/commit/23850d2283e607cbf1fce3ae77b72ce4472885d9
