### ISSUE TITLE
install.sh uses nonexistent directory names

### ISSUE THREAD

**Issue by ttgurney** [socs-dev-env/DoSOCS#16]
the install.sh script clones the appropriate repos but then goes to operate on nonexistent directories named "DoSPDX", "SPDXDash" and "Database" (should be "DoSOCS", "SOCSDashboard" and "SOCSDatabase" respectively)

I have already created a fix for this.

**Comment by zwmcfarland** [comment]
Does this match the fix you created(hopefully you can see this)

https://github.com/socs-dev-env/DoSOCS/compare/master...zwmcfarland-patch-1?quick_pull=1

**Comment by zwmcfarland** [comment]
If not I have also went ahead and submitted it as a pull request https://github.com/socs-dev-env/DoSOCS/pull/19

**Comment by ttgurney** [comment]
Spot on!

**Comment by zwmcfarland** [comment]
Pull https://github.com/socs-dev-env/DoSOCS/pull/19 has been merged, closing issue.

**Comment by ttgurney** [comment]
Please reopen; there are a couple strings that were missed. I will do a quick pull request.
