### ISSUE TITLE
Problem rescanning package

### ISSUE THREAD

**Issue by DanPatten** [socs-dev-env/DoSOCS#17]
If you scan a package the first time it works fine. If you re-scan that same package the following error occurs when it tries to read from cache:

```
  File "DoSPDX.py", line 145, in <module>
    main(sys.argv[1:])
  File "DoSPDX.py", line 134, in main
    spdxDoc.generateSPDXDoc(scanOption)
  File "spdx.py", line 329, in generateSPDXDoc
    tempFileInfo.populateFileInfo(scanOption)
  File "fileInfo.py", line 478, in populateFileInfo
    self.getFileInfo(cached, dbCursor)
TypeError: getFileInfo() takes exactly 4 arguments (3 given)
```

**Comment by ttgurney** [comment]
I had this issue as well, although it was on my very first attempt to scan a package (not a re-scan).

**Comment by zwmcfarland** [comment]
I believe this has been fixed with the latest commit. https://github.com/socs-dev-env/DoSOCS/commit/c0833fc4c0973f80c3a431d40c872d2f2d69a613
