### ISSUE TITLE
README.md - developers link broken

### ISSUE THREAD

**Issue by ttgurney** [socs-dev-env/DoSOCS#21]
Under section "code contributions": Link at "send repo developers an email" returns a 404.

**Comment by zwmcfarland** [comment]
I think it was working, probably just don't have access to that page. Either way I removed it and added a list of developers instead of a link.

Commit: https://github.com/socs-dev-env/DoSOCS/commit/edbbf1642f2f1dffeca4ba90feb0edc3580e53cc
