### ISSUE TITLE
Running DoSPDX with --spdxDocId on a scanned zip generates error

### ISSUE THREAD

**Issue by Kazzira** [socs-dev-env/DoSOCS#23]
Steps to reproduce:

Scan a .zip package
Run DoSPDX with --spdxDocId with spdxDocId of scanned zip

Then this:

Traceback (most recent call last):
  File "DoSPDX.py", line 145, in <module>
    main(sys.argv[1:])
  File "DoSPDX.py", line 128, in main
    result = spdxDoc.getSPDX(spdxDocId)
  File "/media/sf_vbox/DoSOCS-master (1)/DoSOCS-master/src/spdx.py", line 280, in getSPDX
    tempFileInfo = fileInfo.fileInfo()
  File "/media/sf_vbox/DoSOCS-master (1)/DoSOCS-master/src/fileInfo.py", line 35, in __init__
    self.fileChecksum = self.getChecksum()
  File "/media/sf_vbox/DoSOCS-master (1)/DoSOCS-master/src/fileInfo.py", line 433, in getChecksum
    with open(self.filePath, 'rb') as fileIn:
TypeError: coercing to Unicode: need string or buffer, NoneType found

Note: A single file will work.

I have already fixed this by removing the line:

self.fileChecksum = self.getChecksum()

from the __init__ method of fileInfo, since initially fileInfo was called with no filePath specified.  getChecksum() seems to assign a file checksum anyway if the file exists.

**Comment by zwmcfarland** [comment]
Fixed.  As information you will also need to add a call to self.getChecksum() before the very last line of the file, to ensure the file has a checksum before trying to lookup the cached file details by checksum.

This is a perfect example of why we need unit tests, which is my #1 priority for this project right now. This checksum assignment is something I added earlier today to fix another issue, and broke this feature. Unit tests could of caught this for me before I pushed it.

Anyways thanks for catching this issue, it is amazing how much faster we can get this program improved by having more eyes,(I think there is a Linus Torvalds quote about this).

Commit: f50df24
