### ISSUE TITLE
No usage message when passing "-h" or "--help" options

### ISSUE THREAD

**Issue by ttgurney** [socs-dev-env/DoSOCS#26]
Running DoSPDX.py with no arguments or with `--help` does nothing, and with `-h` only shows one line: "Help Documentation". It would be much easier to work with DoSOCS if it followed the convention of printing a usage message when `--help` or `-h` is passed.

I am willing to provide the patch for this.

**Comment by zwmcfarland** [comment]
Yep, simply never got back around to it. My plan was to basically just put the usage. If you want to create a pull request that is great, otherwise I will do it tomorrow afternoon.
